version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      MACRO_COUNTER_CONFIG_PATH: /app/.testing/macro_counter/config.json
      MACRO_COUNTER_STORE_PATH: /app/.testing/macro_counter/store.json
