version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      MACRO_COUNTER_MONGODB_DATABASE: macro_counter
      MACRO_COUNTER_MONGODB_HOST: mongodb
      MACRO_COUNTER_MONGODB_USERNAME: user
      MACRO_COUNTER_MONGODB_PASSWORD: password123
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123
